# -*- coding: utf-8 -*-
"""Calculadora_inteligente1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7fHD6fvRC_UVYICPbS306e6rXiq_kzI

### **Inicio do código:**
"""

# Primeiro, importamos a biblioteca time para realizarmos intervalos de interação no código:
from time import sleep

# Agora, realizamos as boas-vindas ao usuário:
print("Olá, bem-vindo à calculadora inteligente!\nPara iniciarmos, digite dois números para realizarmos a operação:\n")
sleep(1)

# Em seguida, utilizamos o input para recebermos os números que o usuário escolher:
sleep(1)
while True:
    try:
        n1 = int(input("Primeiro número: "))
        n2 = int(input("Segundo número: "))
        break
    except ValueError:
        print("\nErro, digite valores inteiros!\n")

# A seguir, vamos dar as opções de operação ao usuário:
print("\nExcelente! Escolha o tipo de operação que deseja realizar com base nas opções abaixo:")

while True:
    try:
        # Logo em seguida, gravamos a informação dada pelo usuário na variável opcao:
        opcao = int(input("\n (1) Adição\n (2) Subtração\n (3) Multiplicação\n"))
        if opcao in [1, 2, 3]:
            print("")
            break
        else:
            print("Opção inválida! Digite um número inteiro de 1 a 3.")
    except ValueError:
        print(f"\nOpção inválida. Escolha números inteiros entre 1 e 3!")

# Utilizamos em seguida condicionais para darmos prosseguimento ao funcionamento correto do código:
if opcao == 1:
    print(f"Você escolheu adição! Os números {n1} e {n2} somados são iguais a: {n1 + n2}!")

elif opcao == 2:
    print(f"Você escolheu subtração! Os números {n1} e {n2} subtraídos são iguais a: {n1 - n2}!")

elif opcao == 3:
    print(f"Você escolheu multiplicação! Os números {n1} e {n2} multiplicados são iguais a: {n1 * n2}!")

# Pergunta se o usuário deseja continuar ou encerrar
opcao_2 = input("Digite (1) para continuar, ou (2) para encerrar!")

while True:
    try:
        opcao_2 = int(opcao_2)
        if opcao_2 in [1, 2]:
            print("")
            break
        else:
            print("Opção inválida! Digite um número inteiro de 1 a 2")
    except ValueError:
        print("Opção inválida! Digite um número inteiro, ou uma opção válida.")

while opcao_2 == 1:
    print("Vamos novamente! Para iniciarmos, digite dois números para realizarmos a operação:\n")

    while True:
        try:
            n1 = int(input("Primeiro número: "))
            n2 = int(input("Segundo número: "))
            break
        except ValueError:
            print("\nErro, digite valores inteiros!\n")

    print("\nExcelente! Escolha o tipo de operação que deseja realizar com base nas opções abaixo:")

    while True:
        try:
            opcao = int(input("\n (1) Adição\n (2) Subtração\n (3) Multiplicação\n"))
            if opcao in [1, 2, 3]:
                print("")
                break
            else:
                print("Opção inválida! Digite um número inteiro de 1 a 3.")
        except ValueError:
            print(f"\nOpção inválida. Escolha números inteiros entre 1 e 3!")

    if opcao == 1:
        print(f"Você escolheu adição! Os números {n1} e {n2} somados são iguais a: {n1 + n2}!")

    elif opcao == 2:
        print(f"Você escolheu subtração! Os números {n1} e {n2} subtraídos são iguais a: {n1 - n2}!")

    elif opcao == 3:
        print(f"Você escolheu multiplicação! Os números {n1} e {n2} multiplicados são iguais a: {n1 * n2}!")

    # Pergunta novamente se o usuário quer continuar ou encerrar
    while True:
        opcao_2 = input("Digite (1) para continuar, ou (2) para encerrar!")
        try:
            opcao_2 = int(opcao_2)
            if opcao_2 in [1, 2]:
                print("")
                break
            else:
                print("Opção inválida! Digite um número inteiro de 1 a 2")
        except ValueError:
            print("Opção inválida! Digite um número inteiro, ou uma opção válida.")

print("Ok, obrigado por utilizar a calculadora inteligente! Até mais.")